version: 2.1

orbs:
  python: circleci/python@1.5.0
  aws-cli: circleci/aws-cli@3.1
  aws-ecs: circleci/aws-ecs@4.0
  aws-ecr: circleci/aws-ecr@9.0.0
  #aws-code-deploy: circleci/aws-code-deploy@3.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          name: Run tests pytest
          command: pytest
      - run:
          name: Run Flake8
          command: flake8

  build-docker:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build Docker image
          command: docker build -t $USER_NAME_DOCKER/projet_13_python-oc-lettings-fr:$CIRCLE_SHA1 .
      - run:
          name: Push DockerHub
          command: |
              echo $TOKEN_DOCKER | docker login --username $USER_NAME_DOCKER --password-stdin
              docker tag $USER_NAME_DOCKER/projet_13_python-oc-lettings-fr:$CIRCLE_SHA1 $USER_NAME_DOCKER/projet_13_python-oc-lettings-fr:latest
              docker push $USER_NAME_DOCKER/projet_13_python-oc-lettings-fr:$CIRCLE_SHA1
              docker push $USER_NAME_DOCKER/projet_13_python-oc-lettings-fr:latest

  deploy_application_aws:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - aws-ecr/build_and_push_image:
          auth:
              - aws-cli/setup:
                  aws-access-key-id: AWS_ACCESS_KEY_ID
                  aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          profile-name: 615942929624
          dockerfile: dockerfile
          platform: linux/amd64
          push_image: false
          region: eu-west-3
          repo: projet_13_python-oc-lettings-fr
          tag: $USER_NAME_DOCKER/projet_13_python-oc-lettings-fr:latest
      - aws-ecr/push_image:
          region: eu-west-3
          repo: projet_13_python-oc-lettings-fr
          tag: $USER_NAME_DOCKER/projet_13_python-oc-lettings-fr:latest

workflows:
  sample:
    jobs:
      - build-and-test
      - build-docker:
          requires:
            - build-and-test
      - deploy_application_aws:
          requires:
                - build-docker