version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          name: Run tests pytest
          command: pytest
      - run:
          name: Run Flake8
          command: flake8

  build-docker:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build Docker image
          command: docker build -t $USER_NAME_DOCKER/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 .
      - run:
          name: Push DockerHub
          command:
              echo $TOKEN_DOCKER | docker login -u $USER_NAME_DOCKER --password-stdin
              docker tag $USER_NAME_DOCKER/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 $CIRCLE_PROJECT_REPONAME:latest
              docker push $USER_NAME_DOCKER/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
              docker push $USER_NAME_DOCKER/$CIRCLE_PROJECT_REPONAME:latest

workflows:
  sample:
    jobs:
      - build-and-test
      - build-docker:
          requires:
            - build-and-test